In [1]:
import numpy as np
from scipy.spatial.distance import hamming
n=int(input("Enter the value of 'n': "))
a=[None]*n
b=[None]*n
#for i in range (0,n): ; usar numpy implica menos uso computacional y mayor especificidad
a= np.random.randint(2, size=n)
b= np.random.randint(2, size=n)

print(a)
print(b)

[0 0 1 1 1]
[1 1 1 1 0]


In [2]:
from sklearn.neighbors import DistanceMetric
#from sklearn.metrics import hamming_loss
#import numpy as np
#hamming_loss(a,b)
haming_d = hamming(a,b)*len(a)
print(haming_d)

3.0


La medida de Hamming es la fracción de etiquetas diferentes

TypeError: randint() takes at least 1 positional argument (0 given)

In [ ]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)
KNeighborsClassifier(...)
print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))


In [ ]:
from sklearn.neighbors import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')
X = [[0, 1, 2],
         [3, 4, 5]]
dist.pairwise(X)
array([[ 0.        ,  5.19615242],
       [ 5.19615242,  0.        ]])

In [ ]:
ks = range(1,26)
scores = {}
scores_list = []
for k in ks:
  knn = KNeighborsClassifier(n_neighbors=k, p = 2)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  scores[k] = metrics.accuracy_score(y_test, y_pred)
  scores_list.append(metrics.accuracy_score(y_test, y_pred))
print(scores)
print(scores_list)

In [ ]:
#tercero
# la base de datos boston housing  basada en los datos de vivienda de boston en 1970, esta misma es una regresion lienal por sus datos continuos (contables)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_boston

boston = load_boston()
Boston_df = pd.DataFrame(boston['data'], columns = boston['feature_names'])
boston_dataset = load_boston()
X=pd.DataFrame(boston_dataset['data'], columns=boston_dataset.feature_names)
Y=boston_dataset['target']

Labels = boston['target']
names = boston['feature_names']

Boston_df.head()
Boston_df.dtypes
Boston_df.info()
Boston_df.shape

In [ ]:
#print(Boston_df.iloc[:,[0,2,3]])

In [ ]:
Boston_df['CRIM'] = boston['target']
Boston_df.head()

In [ ]:
print(Boston_df.isnull())

In [ ]:
sns.boxplot(Boston_df)

In [ ]:
# <<<<<< Normalizar datos >>>>>>>

In [ ]:
from sklearn.preprocessing import Normalizer
norm_boston = Normalizer().fit(X)
norm_boston = norm_boston.transform(Boston_df)

In [ ]:
sns.boxplot(norm_boston)

#se normalizó para evitar la redundancia de los datos


In [ ]:
sns.heatmap(Boston_df.corr())

In [ ]:
sns.pairplot(Boston_df)